const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=s=>{try{const u=new URL(s,location.origin);return ['http:','https:'].includes(u.protocol)?esc(u.href):''}catch{return ''}};
const cover=p=>p.thumbnail?`<img src="${safe(p.thumbnail)}" alt="${esc(p.title)}" loading="lazy">`:`<div class="type-cover ${esc(p.theme)}"><span class="cover-label">JOSH / PROJECTS</span><span class="cover-type">${esc(p.coverText).replace(/\n/g,'<br>')}</span><span class="cover-bottom">${esc(p.category.split(' · ')[0])}<span>↗</span></span></div>`;
function card(p,i){return `<article class="project-card"><a class="project-link" href="/projects/${encodeURIComponent(p.slug)}/"><div class="thumbnail">${cover(p)}${p.previewVideo?`<video class="preview" muted loop playsinline preload="none" src="${safe(p.previewVideo)}" aria-hidden="true"></video><span class="preview-label">Preview</span>`:''}</div><div class="card-heading"><h3>${esc(p.title)}</h3><span class="card-index">0${i+1}</span></div><p>${esc(p.category)}</p></a></article>`}
function bindPreviews(){document.querySelectorAll('.project-link').forEach(a=>{const v=a.querySelector('video');if(!v)return;let timer;const start=()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;timer=setTimeout(()=>v.play().then(()=>a.classList.add('playing')).catch(()=>{}),200)};const stop=()=>{clearTimeout(timer);v.pause();v.currentTime=0;a.classList.remove('playing')};a.addEventListener('mouseenter',start);a.addEventListener('mouseleave',stop);a.addEventListener('focus',start);a.addEventListener('blur',stop)})}
fetch('/content.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{
const path=decodeURIComponent(location.pathname).replace(/\/$/,'')||'/';const isGallery=path==='/gallery';const p=data.projects.find(p=>path===`/projects/${p.slug}`);document.querySelector('[data-nav="about"]').setAttribute('aria-current',path==='/'?'page':'false');document.querySelector('[data-nav="gallery"]').setAttribute('aria-current',isGallery||p?'page':'false');
if(path==='/'){
document.title=`${data.name} — Mechanical Engineering`;
app.innerHTML=`<section class="intro wrap"><p class="eyebrow">MECHANICAL ENGINEERING · WASHINGTON STATE UNIVERSITY</p><h1>Hi, I’m ${esc(data.name)}.<br><span>I like to build things.</span></h1><div class="intro-bottom"><a class="pill" href="/gallery/">Explore my projects <span>↗</span></a></div></section><section class="about-section"><div class="wrap about-grid"><div class="about-portrait-column"><h2>A little about me.</h2><div class="portrait-box">${data.portrait?`<img src="${safe(data.portrait)}" alt="Portrait of ${esc(data.name)}">`:'<span class="portrait-placeholder" role="img" aria-label="Space for a portrait"></span>'}</div></div><div><p>${esc(data.bio)}</p><p>${esc(data.personal)}</p></div></div></section><section class="wrap selected"><div class="section-heading"><h2>Things I’ve been working on.</h2><a class="text-link" href="/gallery/">View gallery ↗</a></div><div class="project-grid">${data.projects.slice(0,3).map(card).join('')}</div></section>`;
}else if(isGallery){document.title=`Projects — ${data.name}`;app.innerHTML=`<section class="wrap gallery"><p class="eyebrow">THE PROJECT GALLERY</p><h1>Ideas. Made real.</h1><p class="page-subtitle">A collection of builds, experiments, and work in progress.</p><div class="gallery-meta"><span>All projects</span><span>${String(data.projects.length).padStart(2,'0')}</span></div><div class="project-grid">${data.projects.map(card).join('')}</div></section>`
}else if(p){document.title=`${p.title} — ${data.name}`;document.querySelector('meta[name="description"]').content=p.summary;app.innerHTML=`<article class="wrap detail"><a class="text-link back" href="/gallery/">← All projects</a><div class="detail-heading"><p class="eyebrow">${esc(p.category)}</p><h1>${esc(p.title)}</h1><p class="page-subtitle">${esc(p.summary)}</p><span class="stage">${esc(p.year)}</span></div>${p.video?`<video class="main-video" controls playsinline preload="metadata" ${p.thumbnail?`poster="${safe(p.thumbnail)}"`:''} src="${safe(p.video)}">Your browser cannot play this video. <a href="${safe(p.video)}">Download the video</a></video>`:`<div class="detail-cover">${cover(p)}</div>`}<section class="story-row"><h2>Overview</h2><p>${esc(p.description)}</p></section>${p.details.map(d=>`<section class="story-row"><h2>${esc(d.title)}</h2><p>${esc(d.text)}</p></section>`).join('')}${p.photos.length?`<section class="photo-section"><h2>A closer look.</h2><div class="photo-grid">${p.photos.map((f,i)=>`<figure><a href="${safe(f.src)}" target="_blank" rel="noopener"><img loading="lazy" src="${safe(f.src)}" alt="${esc(f.alt||f.caption||p.title+' detail '+(i+1))}"></a>${f.caption?`<figcaption>${esc(f.caption)}</figcaption>`:''}</figure>`).join('')}</div></section>`:''}<div class="project-end"><span>Keep exploring.</span><a class="pill" href="/gallery/">Back to the gallery ↗</a></div></article>`
}else{document.title='Page not found — Josh';app.innerHTML='<section class="wrap intro"><h1>Nothing here yet.</h1><a class="pill" href="/gallery/">Back to projects ↗</a></section>'}
bindPreviews();
}).catch(()=>{app.innerHTML='<section class="wrap intro"><h1>Couldn’t load the portfolio.</h1><p>Please refresh to try again.</p></section>'});
