(function(){
'use strict';
const M=window.PortfolioModel,defaults=window.PortfolioDefaults,$=s=>document.querySelector(s),clone=M.clone;
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const REPO='jleo0312/jleo0312.github.io',API='https://api.github.com/repos/'+REPO;
let data,baseData,baseSha='',key='home',selected='',mode='section',imagePath='',token='',dirty=false,ready=false,device=1200,saving=false,history=[],future=[],assets=new Map(),pendingUpload='',mediaTarget='',newKind='page',draftRecord=null,draftTimer,previewTimer,fieldEditing=false;
const get=(path,fallback='')=>{const value=path.split('.').reduce((o,k)=>o?.[k],data);return value??fallback;};
function set(path,value){const parts=path.split('.');if(parts.some(p=>['__proto__','prototype','constructor'].includes(p)))throw new Error('Invalid field.');let at=data;parts.forEach((p,i)=>{if(i===parts.length-1)at[p]=value;else{if(!at[p]||typeof at[p]!=='object')at[p]=/^\d+$/.test(parts[i+1])?[]:{};at=at[p];if(['heroImage','portraitImage','imageStyle','thumbnailStyle','videoStyle'].includes(p))at.enabled=true;}});}
function status(text){$('#status').textContent=text;}
function mark(){dirty=true;status('Draft changes · not published');clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,500);clearTimeout(previewTimer);previewTimer=setTimeout(preview,120);updateUndo();}
function remember(){history.push(clone(data));if(history.length>60)history.shift();future=[];updateUndo();}
function updateUndo(){$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;}
function mutate(fn){remember();fn();mark();renderAll();}
function sectionList(){return M.sections(data,key,true);}
function section(){return sectionList().find(s=>s.id===selected);}
function sectionPath(){const info=M.pageInfo(data,key),i=sectionList().findIndex(s=>s.id===selected);return info.project?`projects.${data.projects.indexOf(info.project)}.sections.${i}`:info.page?`pages.${data.pages.indexOf(info.page)}.sections.${i}`:`pageLayouts.${key}.sections.${i}`;}
function url(path){return assets.get(path)?.url||path||'';}
function plainField(label,path,type='text',fallback='',hint=''){
 const value=get(path,fallback),attr=`data-path="${escape(path)}"`;
 if(type==='checkbox')return `<label class="field checkbox"><input type="checkbox" ${attr} ${value?'checked':''}>${escape(label)}</label>`;
 return `<label class="field">${escape(label)}${type==='textarea'?`<textarea ${attr}>${escape(value)}</textarea>`:`<input type="${type}" ${attr} value="${escape(value)}">`}${hint?`<small>${escape(hint)}</small>`:''}</label>`;
}
function select(label,path,values,fallback){const value=get(path,fallback);return `<label class="field">${escape(label)}<select data-path="${escape(path)}">${values.map(item=>{const [k,name]=Array.isArray(item)?item:[item,item];return `<option value="${escape(k)}" ${String(k)===String(value)?'selected':''}>${escape(name)}</option>`;}).join('')}</select></label>`;}
function range(label,path,min,max,fallback,unit=''){const value=get(path,fallback);return `<label class="field"><span class="range-label">${escape(label)}<output>${value===0&&path.endsWith('.height')?'Auto':escape(value)+unit}</output></span><input type="range" min="${min}" max="${max}" step="1" data-path="${escape(path)}" data-number="true" data-unit="${unit}" value="${escape(value)}"></label>`;}
function mediaField(label,path,type='image'){const value=get(path);return `<div class="media-field">${type==='image'&&value?`<img src="${escape(url(value))}" alt="${escape(label)}">`:''}${plainField(label,path,'text','','Choose a file or paste an image/video address.')}<div class="button-row"><button data-upload="${escape(path)}" data-media-type="${type}">Upload ${type}</button><button data-library="${escape(path)}">Choose existing</button><button data-clear="${escape(path)}">Clear</button></div></div>`;}
function imageControls(path,{caption=true,position=false}={}){
 return `<details open><summary>Image size and position</summary><div class="presets">${[['Small',40],['Medium',65],['Large',85],['Full width',100]].map(([label,value])=>`<button data-preset="${escape(path)}.width" data-value="${value}">${label}</button>`).join('')}</div>${range('Width',path+'.width',10,100,100,'%')}${range('Height',path+'.height',0,1200,0,' px')}${select('Aspect ratio',path+'.aspect',[['auto','Original proportions'],['square','Square'],['portrait','Portrait · 4:5'],['tall','Portrait · 3:4'],['landscape','Landscape · 4:3'],['wide','Wide · 16:9']],'auto')}${select('Image alignment',path+'.align',[['left','Left'],['center','Center'],['right','Right']],'center')}${position?select('Photo position',path+'.position',[['above','Photo above text'],['below','Photo below text'],['left','Photo left'],['right','Photo right']],'above'):''}${select('Fit',path+'.fit',[['contain','Show whole photo'],['cover','Fill and crop']],'contain')}${range('Crop focus · horizontal',path+'.focalX',0,100,50,'%')}${range('Crop focus · vertical',path+'.focalY',0,100,50,'%')}${range('Space around image',path+'.margin',0,120,0,' px')}${range('Padding inside frame',path+'.padding',0,80,0,' px')}</details>${caption?`<details><summary>Caption</summary>${plainField('Caption',path+'.caption','textarea')}${captionControls(path)}</details>`:''}`;
}
function captionControls(path,visibility=path+'.showCaption'){return `${plainField('Show caption',visibility,'checkbox',true)}${select('Caption position',path+'.captionPosition',[['below','Below photo'],['above','Above photo']],'below')}${select('Caption alignment',path+'.captionAlignment',[['left','Left'],['center','Center'],['right','Right']],'left')}`;}
function layoutControls(path,photo=true){return `<details open><summary>Section layout</summary>${photo?`${select('Photo placement',path+'.imagePosition',[['left','Photo left / text right'],['right','Photo right / text left'],['above','Photo above text'],['below','Photo below text']],'left')}${range('Photo column size',path+'.imageWidth',10,90,56,'%')}${range('Text column size',path+'.textWidth',10,90,44,'%')}`:''}${select('Content width',path+'.contentWidth',[['default','Default'],['narrow','Narrow'],['wide','Wide'],['full','Full width']],'default')}${select('Vertical alignment',path+'.alignment',[['start','Top'],['center','Center'],['end','Bottom']],'center')}${select('Text alignment',path+'.textAlign',[['left','Left'],['center','Center'],['right','Right']],'left')}${select('Text size',path+'.textSize',[['small','Small'],['normal','Medium'],['large','Large']],'normal')}${range('Gap between photo and text',path+'.gap',0,100,46,' px')}${range('Space above section',path+'.spacingTop',0,200,0,' px')}${range('Space below section',path+'.spacingBottom',0,200,0,' px')}${plainField('Show section',path+'.visible','checkbox',true)}</details>`;}
function projectFields(project){const p=`projects.${data.projects.indexOf(project)}`;return `${plainField('Project title',p+'.title')}${plainField('Project address',p+'.slug','text','','Lowercase letters, numbers and dashes. Changing this also changes its link.')}${plainField('Description',p+'.description','textarea')}${plainField('Show in gallery',p+'.showInGallery','checkbox',true)}${plainField('Feature on homepage',p+'.featuredOnHomepage','checkbox',true)}${select('Homepage order',p+'.homepageOrder',[['auto','Automatic'],...Array.from({length:9},(_,i)=>[String(i+1),String(i+1)])],'auto')}${mediaField('Thumbnail',p+'.thumbnail')}${plainField('Image description',p+'.thumbnailAlt')}${imageControls(p+'.thumbnailStyle',{position:true})}${mediaField('Animated thumbnail video',p+'.previewVideo','video')}${select('Thumbnail motion',p+'.thumbnailMotion',[['hover','On hover · automatic on touch'],['loop','Loop automatically'],['still','Still photo only']],'hover')}${select('Thumbnail fit',p+'.thumbnailFit',[['cover','Fill frame'],['contain','Show entire video']],'cover')}${plainField('Cover text when no photo',p+'.coverText','textarea')}${select('Cover color',p+'.theme',[['silver','Silver'],['dark','Dark'],['blue','Blue']],'silver')}`;}
function inspector(){
 const panel=$('#inspector'),info=M.pageInfo(data,key);
 if(mode==='site'){
   panel.innerHTML=`<h2>Website settings</h2>${mediaField('Website icon','siteIcon')}${Object.entries(defaults).map(([group,fields])=>`<details ${group==='home'?'open':''}><summary>${{identity:'Name and browser titles',navigation:'Navigation',home:'Homepage text',gallery:'Gallery text',footer:'Footer',project:'Project labels',carousel:'Slideshow',messages:'Other messages'}[group]}</summary>${Object.entries(fields).filter(([name])=>name!=='siteIcon').map(([name,value])=>{const path=`website.${group}.${name}`,label=name.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase());if(typeof value==='boolean')return plainField(label,path,'checkbox',value);if(name==='source')return select(label,path,[['selected','Selected projects'],['demo','Demo placeholders']],'selected');if(typeof value==='number')return range(label,path,1,30,value,' seconds');return plainField(label,path,'textarea',value);}).join('')}</details>`).join('')}`;return;
 }
 if(mode==='page'){
   panel.innerHTML=`<h2>${escape(info.title)}</h2>${info.project?projectFields(info.project):info.page?`${plainField('Page title',`pages.${data.pages.indexOf(info.page)}.title`)}${plainField('Page address',`pages.${data.pages.indexOf(info.page)}.slug`)}${plainField('Show in navigation',`pages.${data.pages.indexOf(info.page)}.showInNavigation`,'checkbox',false)}`:'<p>Choose a section to edit its content, or use Website settings for shared text and labels.</p>'}<hr><p class="help">The original editor fields remain available in Pages CMS.</p><button id="import-button">Import content backup</button>`;return;
 }
 const s=section();if(!s){panel.innerHTML='<h2>Choose a section</h2><p>Click a section in the preview or add a new one.</p>';return;}
 const p=sectionPath();let fields='';
 if(imagePath){const captionPath=imagePath==='portraitImage'?'personal':imagePath.includes('.photos.')?imagePath.replace(/\.imageStyle$/,'.shortCaption'):imagePath.includes('.sections.')?imagePath.replace(/\.imageStyle$/,'.caption'):imagePath+'.caption';const visibility=imagePath.includes('.sections.')?imagePath.replace(/\.imageStyle$/,'.showCaption'):imagePath.includes('.photos.')?imagePath.replace(/\.imageStyle$/,'.showCaption'):imagePath+'.showCaption';fields=`<p class="help">Selected image</p>${imageControls(imagePath,{caption:false,position:imagePath.endsWith('thumbnailStyle')||imagePath.startsWith('hobbies.')})}${plainField('Caption',captionPath,'textarea')}${captionControls(imagePath,visibility)}<button data-back-section>Back to section</button>`;panel.innerHTML=`<h2>Image controls</h2>${fields}`;return;}
 switch(s.type){
  case 'hero':fields=plainField('Small heading','website.home.eyebrow','textarea',defaults.home.eyebrow)+plainField('Main heading','website.home.headline','textarea',defaults.home.headline)+plainField('Second heading line','website.home.subheadline','textarea',defaults.home.subheadline)+plainField('Button text','website.home.button','text',defaults.home.button)+plainField('Button destination','website.home.buttonLink','text','/?view=gallery')+mediaField('Homepage photo','heroPhoto')+plainField('Photo description','heroPhotoAlt')+imageControls('heroImage');break;
  case 'about':fields=plainField('Section heading','website.home.aboutTitle','text',defaults.home.aboutTitle)+plainField('About me','bio','textarea')+mediaField('About-me photo','portrait')+plainField('Photo description','portraitAlt')+plainField('Caption under the photo','personal','textarea')+captionControls('portraitImage')+imageControls('portraitImage',{caption:false});break;
  case 'hobbies':fields=plainField('Section heading','website.home.hobbiesTitle','text',defaults.home.hobbiesTitle)+plainField('Text under Hobbies','hobbiesIntro','textarea')+Array.from({length:3},(_,i)=>`<details ${i===0?'open':''}><summary>Hobby ${i+1}</summary>${mediaField('Photo',`hobbies.${i}.photo`)}${plainField('Title',`hobbies.${i}.title`)}${plainField('Text',`hobbies.${i}.text`,'textarea')}${imageControls(`hobbies.${i}.imageStyle`,{position:true})}</details>`).join('');break;
  case 'highlights':fields=plainField('Heading','website.home.highlightsTitle','text',defaults.home.highlightsTitle)+plainField('Gallery link text','website.home.galleryLink','text',defaults.home.galleryLink)+range('Seconds between slides','website.carousel.seconds',1,30,2.5,' seconds')+'<p class="help">Mobile shows one project at a time. Choose projects below.</p>'+data.projects.map((project,i)=>`<details><summary>${escape(project.title)}</summary>${plainField('Show in gallery',`projects.${i}.showInGallery`,'checkbox',true)}${plainField('Feature on homepage',`projects.${i}.featuredOnHomepage`,'checkbox',true)}${select('Homepage order',`projects.${i}.homepageOrder`,[['auto','Automatic'],...Array.from({length:9},(_,n)=>[String(n+1),String(n+1)])],'auto')}</details>`).join('');break;
  case 'galleryIntro':fields=plainField('Small heading','website.gallery.eyebrow','text',defaults.gallery.eyebrow)+plainField('Main heading','website.gallery.headline','textarea',defaults.gallery.headline)+plainField('Description','website.gallery.subtitle','textarea',defaults.gallery.subtitle);break;
  case 'galleryGrid':fields=plainField('List label','website.gallery.allProjects','text',defaults.gallery.allProjects)+plainField('Show count','website.gallery.showCount','checkbox',true)+data.projects.map(project=>`<details><summary>${escape(project.title)}</summary>${projectFields(project)}</details>`).join('');break;
  case 'projectIntro':fields=projectFields(info.project);break;
  case 'projectVideo':fields=mediaField('Project video',`projects.${data.projects.indexOf(info.project)}.video`,'video')+imageControls(`projects.${data.projects.indexOf(info.project)}.videoStyle`);break;
  case 'projectPhoto':{const photo=M.photoSource(data,key,s),path=`projects.${data.projects.indexOf(info.project)}.photos.${info.project.photos.indexOf(photo)}`;fields=mediaField('Photo',path+'.src')+plainField('Image description',path+'.alt')+plainField('Heading beside photo',path+'.title')+plainField('Text beside photo',path+'.text','textarea',photo.text??photo.caption??'')+plainField('Short caption under photo',path+'.shortCaption','textarea')+captionControls(path+'.imageStyle',path+'.showCaption')+imageControls(path+'.imageStyle',{caption:false});break;}
  case 'projectThumbnail':{const p=`projects.${data.projects.indexOf(info.project)}`;fields=mediaField('Project cover photo',p+'.thumbnail')+imageControls(p+'.thumbnailStyle',{position:true});break;}
  case 'projectEnd':fields=plainField('Footer text','website.project.endText','text',defaults.project.endText)+plainField('Gallery button','website.project.galleryButton','text',defaults.project.galleryButton);break;
  case 'photoText':fields=mediaField('Photo',p+'.image')+plainField('Image description',p+'.alt')+plainField('Heading',p+'.heading')+plainField('Text beside photo',p+'.text','textarea')+plainField('Caption',p+'.caption','textarea')+captionControls(p+'.imageStyle',p+'.showCaption')+imageControls(p+'.imageStyle',{caption:false});break;
  case 'text':case 'heading':fields=plainField('Heading',p+'.heading')+select('Heading size',p+'.headingLevel',[['h1','Large heading'],['h2','Section heading'],['h3','Small heading']],'h2')+(s.type==='text'?plainField('Paragraphs',p+'.text','textarea'):'');break;
  case 'video':fields=plainField('Heading',p+'.heading')+mediaField('Video file',p+'.video','video')+mediaField('Poster image',p+'.poster')+plainField('Loop video',p+'.loop','checkbox',false)+plainField('Mute video',p+'.muted','checkbox',false)+plainField('Caption',p+'.caption','textarea')+plainField('Show caption',p+'.showCaption','checkbox',true)+plainField('Text',p+'.text','textarea')+imageControls(p+'.imageStyle',{caption:false});break;
  case 'spacer':fields=range('Height',p+'.height',0,200,40,' px');break;
 }
 panel.innerHTML=`<h2>${escape(M.types[s.type])}</h2>${fields}${layoutControls(p,['photoText','projectPhoto','projectThumbnail','hero','about'].includes(s.type))}`;
}
function renderOutline(){
 $('#page-select').innerHTML=M.pages(data).map(info=>`<option value="${escape(info.key)}" ${info.key===key?'selected':''}>${escape(info.kind==='project'?'Project · '+info.title:info.title)}</option>`).join('');
 const values=sectionList();if(!values.some(s=>s.id===selected))selected=values[0]?.id||'';
 $('#sections').innerHTML=values.map((s,i)=>`<div class="section-item ${s.id===selected?'selected':''} ${s.visible===false?'is-hidden':''}" draggable="true" data-index="${i}"><button class="section-select" data-select="${escape(s.id)}">${escape(s.heading||M.types[s.type]||'Section')}</button><div class="section-tools"><button data-action="up" data-index="${i}" aria-label="Move section up" ${i?'':'disabled'}>↑</button><button data-action="down" data-index="${i}" aria-label="Move section down" ${i===values.length-1?'disabled':''}>↓</button><button data-action="duplicate" data-index="${i}">Duplicate</button><button data-action="hide" data-index="${i}">${s.visible===false?'Show':'Hide'}</button><button data-action="delete" data-index="${i}" class="danger">Delete</button></div></div>`).join('');
 $('#open-page').href=M.pageInfo(data,key).url;updateUndo();
}
function renderAll(){renderOutline();inspector();preview();}
function preview(){if(!data||!ready)return;$('#preview').contentWindow.postMessage({portfolioEditor:true,action:'render',data,key,selected,assets:Object.fromEntries([...assets].map(([path,item])=>[path,item.url]))},location.origin);}
function selectSection(id,path=''){selected=id;imagePath=path;mode='section';renderOutline();inspector();$('#preview').contentWindow.postMessage({portfolioEditor:true,action:'select',id},location.origin);}
function fitPreview(){const pane=$('.preview-pane'),width=Math.max(240,pane.clientWidth-36),scale=Math.min(1,width/device),height=window.innerWidth<=800?650:Math.max(360,window.innerHeight-215);$('#preview-shell').style.width=device*scale+'px';$('#preview-shell').style.height=height+'px';$('#preview').style.width=device+'px';$('#preview').style.height=Math.ceil(height/scale)+'px';$('#preview').style.transform=`scale(${scale})`;$('#preview-size').textContent=device+' px';}
function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonical(value[k])]));return value;}
const same=(a,b)=>JSON.stringify(canonical(a))===JSON.stringify(canonical(b));
async function request(path,{method='GET',body,auth=token}={}){const response=await fetch(API+path,{method,cache:'no-store',headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(auth?{Authorization:'Bearer '+auth}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok){let message;try{message=(await response.json()).message;}catch{}throw new Error(response.status===401?'The GitHub token was not accepted.':response.status===403?'GitHub denied this request. Check repository access and Contents permission.':response.status===409||response.status===422?'The repository changed or rejected the save. Your draft is still safe.':message||'GitHub request failed ('+response.status+').');}return response.status===204?{}:response.json();}
function decode64(text){return new TextDecoder().decode(Uint8Array.from(atob(text.replace(/\s/g,'')),c=>c.charCodeAt(0)));}
function encode64(buffer){const bytes=new Uint8Array(buffer);let result='';for(let i=0;i<bytes.length;i+=32768)result+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(result);}
async function readRemote(auth=''){const result=await request('/contents/content.json?ref=main',{auth});return {data:JSON.parse(decode64(result.content)),sha:result.sha};}
function usedAssets(){const text=JSON.stringify(data);return [...assets].filter(([path])=>text.includes(path));}
async function publish(){
 if(!token){$('#connect-dialog').showModal();return;}if(saving)return;
 try{M.validate(data);saving=true;$('#publish').disabled=true;status('Checking the latest saved content…');
 const remote=await readRemote(token);if(!same(remote.data,baseData))throw new Error('The content changed in another editor. Your draft is preserved. Download a backup, then reload the latest website before publishing.');
 const head=await request('/git/ref/heads/main'),commit=await request('/git/commits/'+head.object.sha);
 // Pin the content comparison to this exact parent commit, including changes between reads.
 const pinned=await request('/contents/content.json?ref='+head.object.sha);if(pinned.sha!==remote.sha)throw new Error('The website changed during this save. Try Publish again.');
 const snapshot=clone(data),tree=[{path:'content.json',mode:'100644',type:'blob',content:JSON.stringify(snapshot,null,2)+'\n'}];
 for(const [path,item] of usedAssets()){status('Uploading '+path.split('/').pop()+'…');const blob=await request('/git/blobs',{method:'POST',body:{content:encode64(await item.blob.arrayBuffer()),encoding:'base64'}});tree.push({path:path.slice(1),mode:'100644',type:'blob',sha:blob.sha});}
 const newTree=await request('/git/trees',{method:'POST',body:{base_tree:commit.tree.sha,tree}});
 const next=await request('/git/commits',{method:'POST',body:{message:'Update portfolio from visual editor',tree:newTree.sha,parents:[head.object.sha]}});
 await request('/git/refs/heads/main',{method:'PATCH',body:{sha:next.sha,force:false}});
 baseData=snapshot;baseSha='';dirty=!same(data,snapshot);await saveDraft();status(dirty?'Saved to GitHub. Newer draft edits are still unpublished.':'Saved to GitHub. The website will update after publishing finishes.');
 }catch(error){status(error.message);}finally{saving=false;$('#publish').disabled=false;}
}
async function database(){return new Promise((resolve,reject)=>{const req=indexedDB.open('josh-portfolio-editor',1);req.onupgradeneeded=()=>req.result.createObjectStore('drafts');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function saveDraft(){if(!data)return;try{const db=await database();await new Promise((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put({data:clone(data),baseData:clone(baseData),key,dirty,assets:[...assets].map(([path,item])=>({path,blob:item.blob})),time:Date.now()},'portfolio');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}catch{status('Browser draft storage is unavailable. Use Download changes to keep a backup.');}}
async function loadDraft(){try{const db=await database();const value=await new Promise((resolve,reject)=>{const req=db.transaction('drafts').objectStore('drafts').get('portfolio');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});db.close();return value;}catch{return null;}}
// Small dependency-free ZIP writer. Files are stored without compression, preserving uploaded bytes.
function zip(files){const table=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});const crc=bytes=>{let n=0xffffffff;for(const b of bytes)n=table[(n^b)&255]^(n>>>8);return(n^0xffffffff)>>>0;};let offset=0;const local=[],central=[];for(const file of files){const name=new TextEncoder().encode(file.name),bytes=file.bytes,checksum=crc(bytes),header=new Uint8Array(30+name.length),v=new DataView(header.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,checksum,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,name.length,true);header.set(name,30);local.push(header,bytes);const entry=new Uint8Array(46+name.length),c=new DataView(entry.buffer);c.setUint32(0,0x02014b50,true);c.setUint16(4,20,true);c.setUint16(6,20,true);c.setUint16(8,0x800,true);c.setUint32(16,checksum,true);c.setUint32(20,bytes.length,true);c.setUint32(24,bytes.length,true);c.setUint16(28,name.length,true);c.setUint32(42,offset,true);entry.set(name,46);central.push(entry);offset+=header.length+bytes.length;}const size=central.reduce((n,b)=>n+b.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,files.length,true);v.setUint16(10,files.length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);return new Blob([...local,...central,end],{type:'application/zip'});}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000);}
async function download(){try{M.validate(data);const files=[{name:'content.json',bytes:new TextEncoder().encode(JSON.stringify(data,null,2)+'\n')}];for(const [path,item]of usedAssets())files.push({name:path.slice(1),bytes:new Uint8Array(await item.blob.arrayBuffer())});files.push({name:'UPLOAD.txt',bytes:new TextEncoder().encode('Extract this ZIP. Upload content.json and any media folder to https://github.com/'+REPO+'/upload/main and commit to main. This publishes the complete draft. Keep a backup if you have also made changes in Pages CMS.\n')});downloadBlob(zip(files),'portfolio-content-changes.zip');status('Downloaded your changes. Upload the extracted files to GitHub, or use Publish.');}catch(e){status(e.message);}}
async function upload(file){if(!file)return;try{if(file.size>30*1024*1024)throw new Error('Choose a file smaller than 30 MB.');if(!/^image\/|^video\//.test(file.type))throw new Error('Choose an image, GIF or video file.');const name=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,'-'),path='/media/'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)+'-'+name;assets.set(path,{blob:file,url:URL.createObjectURL(file)});mutate(()=>set(pendingUpload,path));}catch(e){status(e.message);}}
async function mediaLibrary(path){mediaTarget=path;$('#media-dialog').showModal();const found=new Set();function walk(value){if(typeof value==='string'&&/\.(png|jpe?g|webp|gif|svg|ico|mp4|webm|mov)(?:[?#].*)?$/i.test(value))found.add(value);else if(value&&typeof value==='object')Object.values(value).forEach(walk);}walk(data);for(const path of assets.keys())found.add(path);function draw(){$('#media-grid').innerHTML=[...found].map(src=>`<button data-choose-media="${escape(src)}">${/\.(mp4|webm|mov)$/i.test(src)?'▶ Video':`<img src="${escape(url(src))}" alt="">`}${escape(src.split('/').pop())}</button>`).join('')||'<p>No media files found. Upload a file instead.</p>';}
 draw();try{const tree=await request('/git/trees/main?recursive=1',{auth:token});for(const item of tree.tree||[])if(item.type==='blob'&&/\.(png|jpe?g|webp|gif|svg|ico|mp4|webm|mov)$/i.test(item.path))found.add('/'+item.path);draw();}catch{/* Content already referenced by the portfolio is still available. */}}
$('#inspector').addEventListener('focusin',e=>{if(e.target.dataset.path&&!fieldEditing){remember();fieldEditing=true;}});
$('#inspector').addEventListener('focusout',()=>{fieldEditing=false;});
$('#inspector').addEventListener('input',e=>{const control=e.target,path=control.dataset.path;if(!path)return;set(path,control.type==='checkbox'?control.checked:control.dataset.number?Number(control.value):control.value);if(control.type==='range')control.closest('label').querySelector('output').textContent=control.value==='0'&&path.endsWith('.height')?'Auto':control.value+(control.dataset.unit||'');mark();});
$('#inspector').addEventListener('change',e=>{const path=e.target.dataset.path;if(path?.endsWith('.slug')){const info=M.pageInfo(data,key);if(!info){const target=path.startsWith('projects.')?data.projects[Number(path.split('.')[1])]:data.pages[Number(path.split('.')[1])];key=(path.startsWith('projects.')?'project:':'page:')+target.slug;}renderOutline();}else if(path?.endsWith('.title'))renderOutline();});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.close)$('#'+b.dataset.close).close();
 if(b.dataset.select)selectSection(b.dataset.select);
 if(b.dataset.backSection!==undefined){imagePath='';inspector();}
 if(b.dataset.upload){pendingUpload=b.dataset.upload;$('#file-upload').accept=b.dataset.mediaType==='video'?'video/*,image/gif':'image/*';$('#file-upload').value='';$('#file-upload').click();}
 if(b.dataset.library)mediaLibrary(b.dataset.library);
 if(b.dataset.clear)mutate(()=>set(b.dataset.clear,''));
 if(b.dataset.preset)mutate(()=>set(b.dataset.preset,Number(b.dataset.value)));
 if(b.dataset.chooseMedia){mutate(()=>set(mediaTarget,b.dataset.chooseMedia));$('#media-dialog').close();}
 if(b.dataset.device){device=Number(b.dataset.device);document.querySelectorAll('[data-device]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));fitPreview();}
 if(b.dataset.action){const index=Number(b.dataset.index),action=b.dataset.action;mutate(()=>{if(action==='up'||action==='down')M.reorder(data,key,index,index+(action==='up'?-1:1));if(action==='duplicate')selected=M.duplicateSection(data,key,index).id;if(action==='delete')M.deleteSection(data,key,index);if(action==='hide')sectionList()[index].visible=sectionList()[index].visible===false;});}
 if(b.id==='import-button')$('#import-content').click();
});
let dragIndex=-1;$('#sections').addEventListener('dragstart',e=>{const node=e.target.closest('[data-index]');if(node){dragIndex=Number(node.dataset.index);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(dragIndex));}});$('#sections').addEventListener('dragover',e=>e.preventDefault());$('#sections').addEventListener('drop',e=>{e.preventDefault();const node=e.target.closest('[data-index]');if(node&&dragIndex>=0)mutate(()=>M.reorder(data,key,dragIndex,Number(node.dataset.index)));dragIndex=-1;});
$('#add-section').onclick=()=>mutate(()=>{const s=M.makeSection($('#section-type').value),values=sectionList(),index=values.findIndex(v=>v.id===selected);values.splice(index<0?values.length:index+1,0,s);selected=s.id;imagePath='';mode='section';});
$('#page-select').onchange=e=>{key=e.target.value;selected='';imagePath='';mode='section';renderAll();};
$('#site-settings').onclick=()=>{mode='site';imagePath='';inspector();};$('#page-settings').onclick=()=>{mode='page';imagePath='';inspector();};
$('#undo').onclick=()=>{if(!history.length)return;future.push(clone(data));data=history.pop();if(!M.pageInfo(data,key))key='home';mark();renderAll();};$('#redo').onclick=()=>{if(!future.length)return;history.push(clone(data));data=future.pop();mark();renderAll();};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!e.target.matches('input,textarea,[contenteditable]')){e.preventDefault();$(e.shiftKey?'#redo':'#undo').click();}});
$('#connection').onclick=()=>{if(token){token='';$('#connection').textContent='Connect GitHub';status('Disconnected. Your draft remains saved in this browser.');}else $('#connect-dialog').showModal();};
$('#connect-form').onsubmit=async e=>{e.preventDefault();const value=$('#token').value.trim();try{await request('',{auth:value});token=value;$('#token').value='';$('#connect-error').textContent='';$('#connect-dialog').close();$('#connection').textContent='Disconnect GitHub';status('Connected. Use Publish to save your draft to GitHub.');}catch(error){$('#connect-error').textContent=error.message;}};
$('#publish').onclick=publish;$('#download').onclick=download;$('#file-upload').onchange=e=>upload(e.target.files[0]);
$('#import-content').onchange=async e=>{try{const imported=M.upgrade(JSON.parse(await e.target.files[0].text()));M.validate(imported);mutate(()=>{data=imported;key='home';selected='';});}catch(error){status(error.message);}};
function newDialog(kind){newKind=kind;$('#new-title').textContent=kind==='page'?'New page':'New project';$('#new-name').value='';$('#new-slug').value='';$('#new-error').textContent='';$('#new-dialog').showModal();}
$('#new-page').onclick=()=>newDialog('page');$('#new-project').onclick=()=>newDialog('project');$('#new-name').oninput=e=>{$('#new-slug').value=e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');};
$('#new-form').onsubmit=e=>{e.preventDefault();const title=$('#new-name').value.trim(),slug=$('#new-slug').value.trim();const trial=clone(data);if(newKind==='project')trial.projects.push({title,slug});else{trial.pages||=[];trial.pages.push({title,slug});}try{M.validate(trial);}catch(error){$('#new-error').textContent=error.message;return;}mutate(()=>{if(newKind==='project'){data.projects.push({title,slug,showInGallery:true,featuredOnHomepage:false,photos:[]});key='project:'+slug;}else{data.pages||=[];data.pages.push({title,slug,showInNavigation:false,sections:[{...M.makeSection('heading'),heading:title}]});key='page:'+slug;}selected='';imagePath='';mode='section';});$('#new-dialog').close();};
window.addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==$('#preview').contentWindow||!event.data?.portfolioPreview)return;const msg=event.data;if(msg.action==='ready'){ready=true;preview();}if(msg.action==='select')selectSection(msg.id,msg.imagePath||'');if(msg.action==='resize-start'){remember();selected=msg.id;imagePath=msg.path;mode='section';renderOutline();}if(msg.action==='resize'){set(msg.path+'.width',msg.width);dirty=true;}if(msg.action==='resize-end'){mark();inspector();}});
$('#preview').addEventListener('load',()=>{ready=true;preview();});new ResizeObserver(fitPreview).observe($('.preview-pane'));window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
$('#restore-draft').onclick=()=>{data=M.upgrade(draftRecord.data);baseData=draftRecord.baseData;key=M.pageInfo(data,draftRecord.key)?draftRecord.key:'home';for(const item of draftRecord.assets||[])assets.set(item.path,{blob:item.blob,url:URL.createObjectURL(item.blob)});dirty=true;$('#draft-dialog').close();renderAll();status('Draft restored · not published');};$('#discard-draft').onclick=()=>{$('#draft-dialog').close();saveDraft();};
(async()=>{try{let remote;try{remote=await readRemote();}catch{const response=await fetch('/content.json?editor='+Date.now(),{cache:'no-store'});if(!response.ok)throw new Error('Could not load portfolio content.');remote={data:await response.json(),sha:''};}baseData=clone(remote.data);baseSha=remote.sha;data=M.upgrade(remote.data);renderAll();fitPreview();$('#preview').contentWindow.postMessage({portfolioEditor:true,action:'ping'},location.origin);status('Ready · changes stay in your draft until you publish');draftRecord=await loadDraft();if(draftRecord?.dirty&&!same(draftRecord.data,data))$('#draft-dialog').showModal();}catch(error){status(error.message);}})();
})();
